### ISSUE TITLE
Spikesorters collision when spikeforest installed.

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spiketoolkit#182] opened 2019-06-29 15:20 UTC
This is a strange one... but when I don't have spikeforest installed, everything works well with the new spikesorters changes. However, when spikeforest is installed, it tries to import spikesorters from spikeforest and everything breaks.

Can anyone else reproduce this bug? I had to uninstall spikeforest to import spiketoolkit with this bug.

**Comment by alejoe91** [comment] 2019-06-30 12:07
I can't reproduce the issue. Maybe you have to install spikeforest after spiketoolkit. What error do you get @colehurwitz?

**Comment by colehurwitz** [comment] 2019-06-30 12:47
Basically, if I have both installed (I tried installing spikeforest after spiketoolkit as well) then the spikesorters packages will be the one used by spikeforest, not us. So it shows more spike sorters (like JRclust), but it doesn't have the sorter_dict or sorter_list that we do.

**Comment by alejoe91** [comment] 2019-06-30 12:51
ahh you have to update spikeforest! Now the spike forest sorters are spikeforestsorters (https://github.com/flatironinstitute/spikeforest)

**Comment by colehurwitz** [comment] 2019-06-30 12:53
Oooh. I think the pypi package is still behind since I was installing with pip. The updated release should fix all of this then.

**Comment by alejoe91** [comment] 2019-06-30 12:54
Yep, try installing from sources to double check, then we can close the issue

**Comment by colehurwitz** [comment] 2019-06-30 12:57
Yep, that fixed it. Might want to leave the issue open and tag @magland since the sooner that is fixed on the pypi version the better. I know there is still work to merge spiketoolkit and spikeforest, however.

**Closed** 2019-08-22 16:06 UTC
