### ISSUE TITLE
Implementation of a new sorter

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#39] opened 2019-02-06 09:06 UTC
Hi all.
I am about to implement tridesclous here.
Here some feeling about the code structure and the dificulties I could have.

**Comment by samuelgarcia** [comment] 2019-02-06 09:06
First I think that sorter should be implemented with python classes instead of function.

**Comment by samuelgarcia** [comment] 2019-02-06 09:08
Name of function (or classes) should not be the same name as the module itself (klusta - klusta).
We could have some conflict problem very soon with such a choice.

**Comment by samuelgarcia** [comment] 2019-02-06 09:10
A global list of all sorter should be written somewhere.
In the current state we must modify sorter/__init__.py and sorter/tools.py (sortingThread).

A list of classes should be more convinient in many places.

**Comment by samuelgarcia** [comment] 2019-02-06 09:12
For now I don't really understand how a sorter will get the geometry of the probe (aka PRB file).
Is it a necessary kargs ? Or a recommanded kargs ?

**Comment by samuelgarcia** [comment] 2019-02-06 09:20
Import module should not be done in the function itself.

Maybe this approach should be easier in each module:
```python
try:
    import klusta
    HAVE_KLUSTA = True
except ImportError:
    HAVE_KLUSTA = False
```
And so the the ```HAVE_KLUSTA``` could be usefulll as a class attr to include the sorter (or not) in a full list.

**Comment by alejoe91** [comment] 2019-02-06 09:52
Hi @samuelgarcia!

Thanks for the suggestions/comments.

- ***First I think that sorter should be implemented with python classes instead of function.***
We opted for functions instead of classes because spike sorting sounded more like an input-output function. However, I see he benefits of using a class (e.g. storing params etc.), but it would also probably be less direct in the execution of spike sorting as it would require at least to instantiate the object and to run the sorter. Any other reason why you would suggest a class? Potentially each sorter could be derived from a base sorter class as well. @magland what do you think?

- ***Name of function (or classes) should not be the same name as the module itself (klusta - klusta).
We could have some conflict problem very soon with such a choice.***
I agree, I'll rename it

- ***A global list of all sorter should be written somewhere.***
Do you think this could be done automatically? like writing a `discover_sorters` in the `__init__.py` that looks through the files? I agree that it would be handy to have a list of available sorters

- ***For now I don't really understand how a sorter will get the geometry of the probe (aka PRB file).
Is it a necessary kargs ? Or a recommanded kargs ?***
The probe information can be loaded from `.prb` or `.csv` files using spike extractors and information as `location` and `group` are saved as channel properties:
```
recording = se. SomeRecordingExtractor('path-to-file')
# load probe file
recording = se.loadProbeFile(recording, 'path-to-probefile')
# access location and group
recording.getChannelProperty(0, 'location')
-- [0, 0]
recording.getChannelProperty(0, 'group')
-- [0]
```
If `location` or `geometry` information is not provided, a dummy one is created.

- ***Import module should not be done in the function itself.***
Is there a specific reason why it should be done outside the function? speeding up? I see your suggestion as a possible alternative approach, but the idea of having it in the function is to provide install information in case the sorter is attempted to be used and not installed. 

Let's discuss about possible changes :)
Alessio

**Comment by samuelgarcia** [comment] 2019-02-06 10:22
Thank for that quick answers.
Of course I can help to implement theses thing if you like the suggestions.

**Comment by samuelgarcia** [comment] 2019-02-06 10:33
The main reason of classe is that we could have some usefull attributes like:
  * installed = True/False
  * default_params = {...}
  * default_params_by_dataset = {...}
and at least one method:
  * run_sorter(**kargs)

And so we could have 2 functions like:
  * get_all_sorter_classes
  * get_all_installed_sorter_classes

classes do not exclude a function shortcut like this
```python
class KlustaSorter:
    installed = HAVE_KLUSTA
    def run(self, **karg):
        assert self.installed
        ...

def run_klusta(**kargs):
    return KlustaSorter().run(**kargs)
```

**Comment by alejoe91** [comment] 2019-02-06 12:20
Hi @samuelgarcia 

The helper function sounds good and if we give the proper naming it should not break any of the examples.

Can you create a branch so we can implement those updates?

Thanks for the help!
Alessio

**Comment by samuelgarcia** [comment] 2019-02-06 13:16
I will but first I will try to implement tridesclous :)

**Comment by samuelgarcia** [comment] 2019-02-14 12:15
@alejoe91 @colehurwitz31 

I started working on the class approach.

I have a question.

Some (but not all) sorter have a **by_property**, **parallel** kargs which internally call **_spikeSortByProperty** and **_parallelSpikeSorting** I don't anderstand totally  by reading the code the goal of this.
Is it something that could be shared by all sorter (aka available at bas class level) or is it a particular thing only for a few one.

I don't get the stuff.

Some help would be great.

**Comment by samuelgarcia** [comment] 2019-02-14 12:21
For parralel I get it, it should be available for all= with more option ('thread' or 'multiprocessing' or ...)

For "by_property" is it the way you deal "channel_groups" ?
In the prb file a channel_group is several channel that have to be sroter independently from others (aka diffrerente probe).
I will try to put also in class but will need help for this.

**Comment by colehurwitz31** [comment] 2019-02-14 12:47
Hi Sam,

I did not implement any of the spikesorters, however, I think @alejoe91 could give some more insight into the purpose of _spikeSortByProperty than I can. I looked at the documentation and I couldn't figure out what it does. I do think it was designed to deal with channel groups or something similar.

I agree about the parallel changes you are recommending. 

Cole

**Comment by samuelgarcia** [comment] 2019-02-14 14:29
Ok thanks.

Is there a documentation yet somewhere ?

**Comment by alejoe91** [comment] 2019-02-14 14:35
Hi @samuelgarcia 

Yes the idea is that you can sort separately based on a poperty, such as  `group`. We use it for tetrodes.
Basically the _spikeSortByProperty splits the recording in subrecordingextractors, runs spikesorting on each of them, and then reassembles the output with a multisortingextractor.

I agree that we should allow to choose between threading and multiprocessing implementation.
It should also be available to all spikesorters and it could be probably be handled by the base class.

Thanks for helping out with this!

Alessio

**Comment by samuelgarcia** [comment] 2019-02-14 14:40
OK. So it was my guess.

Globally, the channel groups (ak splitting tetrodes) should be cristal clear in the API and totally explicit.
Grouping then with propeties should be an helper and not the entry point of grouping.

I will try to propose something in the class API for this grouping that do not break this behavior but make it more flexible and explicit.

For instance tridesclous totally (and circus too) deal with this multi channel groups but the implementation here do not reflect that.


Thanks.

**Comment by alejoe91** [comment] 2019-02-14 14:55
If the by_property argument is not used, klusta, spyking-circus, and I guess trideclous will deal with the different groups because that information will be used when writing the probe files.

For example, using klusta, when the saveProbeFile funcion is called then it will contain the grouping info, used then by the algorithm.

**Comment by samuelgarcia** [comment] 2019-02-14 14:58
I am not sur to get the workflow : how klusta does known that there are several groups.
If it is already in the PRB file, why this extra "by_property" ?

Have you seen the PR ?

**Comment by samuelgarcia** [comment] 2019-02-14 15:07
One thing I did not anderstand when implementing tridesclous is :
when there are sevral channel groups, how the sorter known on whicj channel group to make the computation ? On all by default ?

I need to add this in the tridesclous wrapper.

Here also, I have the strong feeling that all SortingExtractor should be MultiSortingExtractor with n=1 when there only channel group so this would avoid ugly if ... else ... to diferenciate **one** vs **sevral** channel group case. If it is always coded via a list even if 1, evry thing should be easier via a loop instaed.
Further more for the parralel stuff.

**Comment by alejoe91** [comment] 2019-02-14 15:10
So the basic use case would require the user to load the probe file before running spike sorting:

```
import spikeestractors as se
import spiketoolkit as st

recording = se.SomeRecordingExtractor(path)
recording = se.loadProbeFile(recording, probe-file-path)
sorting = st.sorters.klusta(recording)
```
The last line rewrites the probe file in klusta format (adding the adjacency). The by_property allows also to process groups completely separately, as many people do for tetrodes, for example. I think this implementation allows the user to choose either method. The splitting by property also becomes handy because then also waveforms can be extracted only by group (and this is helpful in phy for example).

It probably needs a more ordered rewrite, but I think that we should keep the underlying idea :)

Also, by_property could be something different than groups, for example brain regions, or layers, etc.

I have seen the PR and it looks good at a first sight. I'm in a train right now with limited internet access. I will give a closer look tomorow!

**Comment by samuelgarcia** [comment] 2019-02-14 15:19
Ok. I will do.

In tdc, channel group are in any case computed independently.

In TDC and SC waveforms are only extracted only for the belonging channel.

**Comment by alejoe91** [comment] 2019-02-14 15:31
I see. Actually we had in mind that the waveforms should not be loaded by default from the spikesorters, as this could result in filling the memory and they might not be required for some applications. Hence, we have the postprocessing module which computes waveforms, templates, pca scores, etc.
This also goes in the direction of standardizing the analysis and validation methods. The postprocessing.getUnitWaveform() function can also be run with the by_property argument. But the group property is loaded in the SortingExtractor object only when the data are sorted with the parallel sorting at the moment. It would be nice to load the group information to all the sorted units whenn when spike sorting is not run in parallel, but this would require getting this info from each spike sorting output. 

Definitely doable though!

**Comment by alejoe91** [comment] 2019-02-20 16:22
@samuelgarcia 
Can I close this?

**Comment by samuelgarcia** [comment] 2019-02-20 19:25
Yes.

I will evently reformulate some proposal in splitted issue or PR.

**Closed** 2019-02-20 19:27 UTC
