### ISSUE TITLE
'WhitenRecording' object has no attribute 'getChannelIds'

### ISSUE THREAD

**Issue by nahawtho** [SpikeInterface/spiketoolkit#90] opened 2019-04-21 11:37 UTC
I am trying to use sorting_MS4 = st.sorters.run_mountainsort4(recording=RX, detect_sign=-1, adjacency_radius=-1, output_folder='tmp_MS4'). 

I am running into problematic relics in the code, like I know getChannelIds is now get_channel_ids() (naming problem). Despite renaming the members to get_channel_ids() get_channel_properties() in ml_ms4alg/mountainsort4.py and so fourth, I cannot narrow in on where WhitenRecording is -- and how exactly it is bugging up this code. I believe I have all the correct installations, and I am installing MS with conda. 

Please let me know if there is anything I can do. I will try to sort -> mda output (old way) and use an extractor from mda to visualize for now. 
I believe the mountainsort_examples/ml_ms4alg/ml_ms4alg/mountainsort4.py file at least needs an update to keep names the same accross the board, and probably wherever WhitenRecording is needs an update too -- to apply the channel ID attribute with the same naming/structure.

Thanks from UCSC,
-Nico

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-1ebd3c79aba7> in <module>
      1 #sorting_MS4 = st.sorters.run_mountainsort4(recording=RX, detect_sign=-1, adjacency_radius=-1, output_folder='tmp_MS4')
      2 
----> 3 SX2 = st.sorters.run_mountainsort4(RX)
      4 
      5 print('Unit ids = {}'.format(SX2.get_unit_ids()))

~/conda/envs/myenv1/lib/python3.6/site-packages/spiketoolkit/sorters/sorterlist.py in run_mountainsort4(*args, **kargs)
     69 
     70 def run_mountainsort4(*args, **kargs):
---> 71     return run_sorter('mountainsort4', *args, **kargs)
     72 
     73 def run_ironclust(*args, **kargs):

~/conda/envs/myenv1/lib/python3.6/site-packages/spiketoolkit/sorters/sorterlist.py in run_sorter(sorter_name_or_class, recording, output_folder, delete_output_folder, grouping_property, parallel, debug, **params)
     52                          parallel=parallel, debug=debug, delete_output_folder=delete_output_folder)
     53     sorter.set_params(**params)
---> 54     sorter.run()
     55     sortingextractor = sorter.get_result()
     56 

~/conda/envs/myenv1/lib/python3.6/site-packages/spiketoolkit/sorters/basesorter.py in run(self)
     85         if not self.parallel:
     86             for i, recording in enumerate(self.recording_list):
---> 87                 self._run(recording, self.output_folders[i])
     88         else:
     89             # run in threads

~/conda/envs/myenv1/lib/python3.6/site-packages/spiketoolkit/sorters/mountainsort4/mountainsort4.py in _run(self, recording, output_folder)
     82             clip_size=p['clip_size'],
     83             detect_threshold=p['detect_threshold'],
---> 84             detect_interval=p['detect_interval']
     85         )
     86 

~/mountainsort_examples/ml_ms4alg/ml_ms4alg/mountainsort4.py in mountainsort4(recording, detect_sign, clip_size, adjacency_radius, detect_threshold, detect_interval, num_workers)
     14   MS4=MountainSort4()
     15   MS4.setRecording(recording)
---> 16   geom=_get_geom_from_recording(recording)
     17   MS4.setGeom(geom)
     18   MS4.setSortingOpts(

~/mountainsort_examples/ml_ms4alg/ml_ms4alg/mountainsort4.py in _get_geom_from_recording(recording)
     42 
     43 def _get_geom_from_recording(recording):
---> 44   channel_ids=recording.getChannelIds()
     45   M=len(channel_ids)
     46   location0=recording.getChannelProperty(channel_ids[0],'location')

AttributeError: 'WhitenRecording' object has no attribute 'getChannelIds'

**Comment by alejoe91** [comment] 2019-04-21 11:57
Hi Nico! 

Thanks for the support. As we went through a round of refractoring for spikeextractors and spiketoolkit and ms4 uses the API internally, we went around by adding a patch for ms4.

Can you try to install it from this repo?

https://github.com/alejoe91/ml_ms4alg

Cheers
Alessio

**Comment by colehurwitz31** [comment] 2019-04-21 11:58
Hi Nico,

Thanks for letting us know. We are aware of this issue and will hopefully be fixing it soon. The problem is that ml_ms4alg has its own internal spikeextractors that is no longer compatible with spikeextractors.

Maybe @magland can update mountain sort with Alessio's patch so that it can be run with spikeinterface's API: https://github.com/alejoe91/ml_ms4alg

Best,

Cole

**Comment by nahawtho** [comment] 2019-04-22 02:34
This appears to be working. The developer installation helped! Thanks

**Comment by colehurwitz31** [comment] 2019-04-22 10:12
I think we should leave this open until the original ml_ms4alg is fixed otherwise people will keep running into this issue.

**Comment by alejoe91** [comment] 2019-05-08 17:33
this is fixed with the latest ml_ms4alg release (tag 0.3.0 https://github.com/magland/ml_ms4alg/tree/0.3.0)

**Closed by alejoe91** 2019-05-08 17:33 UTC
