### ISSUE TITLE
export_to_phy ValueError: feature values should have the same length as the spike train

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#317] opened 2020-04-01 09:44 UTC
Hi :)
There a new bug appear in pr #315 . It seems that only a subpart of waform is exctract even if pca feature is True

Traceback (most recent call last):
  File "spikeinterface_class.py", line 220, in <module>
    if not os.path.isdir(tmp + "/tmp"):
  File "spikeinterface_class.py", line 97, in run_ms
    st.postprocessing.export_to_phy(recording_prb, sorting_MS4, 
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1018, in export_to_phy
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1440, in _get_phy_data
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1290, in _get_quality_metric_data
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 619, in get_unit_amplitudes
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spikeextractors-0.7.4-py3.8.egg/spikeextractors/sortingextractor.py", line 123, in set_unit_spike_features
ValueError: feature values should have the same length as the spike train

**Comment by alejoe91** [comment] 2020-04-01 09:46
Hi! do you mean that all waveforms files are the same? waveforms_0.raw, waveforms_1.raw ...etc?

**Comment by alejoe91** [comment] 2020-04-01 09:47
It seems that the error os raised by amplitudes, not waveforms. I'll have a look

**Comment by llobetv** [comment] 2020-04-01 09:51
I make an error, I edit my comment. I have the fealing that even with extract_pc_features True there is only subpart of waveform exctracted

**Comment by llobetv** [comment] 2020-04-01 09:53
Plus if pc are not exctracted this line doesn't work:
save_property_or_features=save_property_or_features, peak=amp_peak,
max_spikes_per_unit=max_spikes_for_amplitudes,
frames_before=amp_frames_before, frames_after=amp_frames_after,
seed=seed, memmap=memmap, return_idxs=True)

and also give the same error as before

**Comment by alejoe91** [comment] 2020-04-01 09:53
I see what the problem is. amplitudes should always be extracted for all spikes

**Comment by alejoe91** [comment] 2020-04-01 09:59
Fixing it in the current PR

**Comment by alejoe91** [comment] 2020-04-01 10:38
@llobetv it should all be fixed in https://github.com/SpikeInterface/spiketoolkit/pull/315

Note that you have to pull the latest master branch in spikeextraxtors in order for it to work. Let me know if that fixes the issue/s

**Comment by llobetv** [comment] 2020-04-01 11:48
Now I got this:

Traceback (most recent call last):
  File "spikeinterface_class.py", line 291, in <module>
    si.run_ms(file_path, prb_file, ms4_params, numchan, sampling_frequency, 
  File "spikeinterface_class.py", line 97, in run_ms
    st.postprocessing.export_to_phy(recording_prb, sorting_MS4, 
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 992, in export_to_phy
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1473, in _get_phy_data
  File "/users/nsr/llobet/miniconda2/envs/spikeinterface/lib/python3.8/site-packages/spiketoolkit-0.5.2-py3.8.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1516, in _select_max_channels_from_templates
ValueError: 150 is not in list

**Comment by alejoe91** [comment] 2020-04-01 12:04
Found the bug :) I had to swap axes! Check it now! And thanks again for the testing

**Comment by llobetv** [comment] 2020-04-01 12:21
It works perfectly now :)

**Closed** 2020-04-01 12:40 UTC

**Comment by MingChingChiang** [comment] 2020-05-09 07:01
Hi, 
When I try to export my sorted file to phy, I got the same error message when executing this code:
sorting_MS4 = ss.run_mountainsort4(recording=recording, **default_ms4_params, grouping_property='group', output_folder=OUT_MS4, verbose=True)

My error messages are:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-d50ab75d9dec>", line 5, in <module>
    output_folder=MS4_Phy, verbose=True)
  File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 984, in export_to_phy
    max_channels_per_template, **kwargs)
  File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1412, in _get_phy_data
    seed=seed, compute_pc_features=compute_pc_features)
  File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 1232, in _get_quality_metric_data
    max_channels_per_waveforms)
  File "/Users/Ming-Ching/Documents/Python_Project/SI/venv/lib/python3.7/site-packages/spiketoolkit-0.6.1-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 288, in get_unit_waveforms
    sorting.set_unit_spike_features(unit_id, 'waveforms', waveform_list[i], indexes=spike_index_list[i])
TypeError: set_unit_spike_features() got an unexpected keyword argument 'indexes'

I've updated to the latest version of spiketoolkit and spikesorters, but don't know how to fix the problem.

Is it possible that because of the grouping properties, since I previously have successfully exported the ungrouped data to phy-readable format.
