### ISSUE TITLE
get_unit_waveforms memory consuption depend of n_jobs

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#337] opened 2020-04-17 12:15 UTC
Hi,

I don't understand exactly why but if I call get_unit_waveforms from postprocessing with n_jobs > 1 I get an increased of the memory consumption proportional to n_jobs. Even if I ask to exctract a really small number of waveform. 
With n_jobs=6, number of waveform=100 and 64 channels it takes more than 16 Gb of RAM

If n_jobs=1 their is no increased of memory consumption.

Cheer,
Victor

**Comment by alejoe91** [comment] 2020-04-17 12:34
HI Victor,

Can you make sure you have the latest master for both spikeextraxtors and spiketoolkit?
The `memmap` option should be enabled by default.

What is your extractor type? This might affect the performance as well.

Cheers,
Alessio

**Comment by llobetv** [comment] 2020-04-17 12:56
memap is True and I try after uptate and it is still the same.
I used phy exctractor.

**Comment by llobetv** [comment] 2020-04-17 13:01
And  files created in tmp are 800 ko so I don't see how it could consume so much memory

**Comment by alejoe91** [comment] 2020-04-17 13:16
The recording extractor is PhyRecordingExtractor or the sorting one?

**Comment by llobetv** [comment] 2020-04-17 14:01
my bad, it's the sorting one, the recording one is BinDatRecordingExtractor

**Comment by alejoe91** [comment] 2020-04-17 14:38
Then it's really strange, unless the spike trains are very populated. Let me try to explain better: to get waveforms, first we have to load the waveforms in memory and dump them to the memmap file. Now, if you have several jobs, this is done in parallel for each job..it's still very strange that you get such a high RAM usage. I would expect a RAM usage of around: 6 * 100 * 64 * 150 (samples) * 4 (bytes) (give or take).

Did you install spikeextractors from master or from pip? There was a bug in the bindat extractor that I fixed, but it's not in the pip verson yet

**Comment by llobetv** [comment] 2020-04-18 13:17
I install it from master.
I  agree with you but here each core add around 1.6Go, and if I increased max_spikes_per_unit to 1000 it doesn't change so much thing.

**Comment by alejoe91** [comment] 2020-04-18 13:20
Can you paste here a short script that reproduces it? I'll look into it and try to replicate it

**Comment by llobetv** [comment] 2020-04-18 13:43
The issue is link to the size of the .dat file, 7.2Go give me really big increase per n_job (1.6Go) and 580 Mo give me small increase (0.24Go)

```
import spikeextractors as se
import spiketoolkit as st

import numpy as np

ana_folder = "/media/llobet/Flash/test_spikeinterface/test_data/analysis/phy/"
dat_folder = "/media/llobet/Flash/test_spikeinterface/test_data/data.dat"

n_jobs = 8

sampling_frequency = 30000
numchan = 64
dtype = np.int16

sorting = se.PhySortingExtractor(ana_folder)
recording = recording = se.BinDatRecordingExtractor(dat_folder, sampling_frequency, numchan, dtype)

waveforms = st.postprocessing.get_unit_waveforms(recording, sorting,
                                                 ms_before=1,
                                                 ms_after=1, 
                                                 max_channels_per_waveforms=None, 
                                                 max_spikes_per_unit=100,
                                                 memmap=True,
                                                 n_jobs=n_jobs,
                                                 verbose=True,
                                                 save_property_or_features=False, 
                                                 recompute_info=False)
```

**Comment by llobetv** [comment] 2020-04-18 13:50
which is exactly what you expected as memory consumption

**Comment by alejoe91** [comment] 2020-04-18 13:58
How many cpus do you have? Is n_jobs < n_cpus? do you get 3.2 if you use n_jobs=2?

**Comment by alejoe91** [comment] 2020-04-18 14:18
@llobetv I think the problem comes from the joblib backend. 

The default is `loky`, but somehow it fails at closing the jobs and it causes an increase in memory consumption

![image](https://user-images.githubusercontent.com/17097257/79640048-b67a5b80-818f-11ea-9a92-93558a861c75.png)

When I use `threading`  as backend, the memory consumption is nearly 0 and jobs are properly handled. Can you try to see if that works for you as well?

You just need to change these lines ([1](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L258) and [2](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L258)) to:

`output_list = Parallel(n_jobs=n_jobs, backend='threading')(`

Let mw know if that solves it and I'll make `threading` the default. Which OS are you using by the way?

**Comment by llobetv** [comment] 2020-04-18 16:11
I have 8 logic cores, on Ubuntu 18.04.

When i change n_jobs from 1 to 2 and 2 to 3 , memory consumption increase each time of 1.6go

I change thease lines but it didn't solve the issue.

**Comment by samuelgarcia** [comment] 2020-04-20 06:41
Hi all.
I read this very fastky but if you have 10 worker in 10 processes then then file will be open 10 times and the OS will create 10 cache (because memmap) for this file. As the job is very veryr io cosumming (random acces to get small snippet) then cache can be important.

Using the threading, as do @alejoe91 do open 1 file and so one cache but it will not speedup the global process.

Note that here we parralize across units which is a bad choice by design to speedup the operation.
Since each unit fire acrros the entirde file each subprocess have to run randomly througth the entire file. Totally unefficient.

A better aproach would to paralize across chunksize in file. In short we could spli the file in 8 part and each worker would read all waveforms from all units for one part. My guess here is that the memory footprint would be smaller.

**Comment by alejoe91** [comment] 2020-04-20 15:57
@llobetv can you try to avoid passing the `PhySortingExtractor`? 

You can dump it to npz and pass the npz instead:
```
se.NpzSortingExtractor(sorting, 'test.npz')
sorting_npz = se.NpzSortingExtractor('test.npz')
```

I think that the problem could that the `PhySortingExtractor` loads several things (like amplitudes, pc_features...). The joblib mechanism re-loads the extractors in each jobs, and that could explaint at least in part the memory issue

**Comment by llobetv** [comment] 2020-04-21 08:41
Hi @alejoe91,

It solve the issue.

You're last pull request that remove dump when n_jobs=1 also increase a lot the speed with phy sorting and n_jobs=1. (As you say .dump() generate probably load for each waveform exctraction)

**Comment by alejoe91** [comment] 2020-04-21 15:08
@llobetv note that now you can also use `sorting_cache = se.CacheSortingExtractor(sorting)` (which automatically saves the sorting to npz).

I'll close this then!

**Closed by alejoe91** 2020-04-21 15:08 UTC
