### ISSUE TITLE
spiketoolkit, spikeextractors and spikewidgets should be merged in one unique code base

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#42] opened 2019-02-13 09:15 UTC
The more I explore this project, the more my feeling about **"spiketoolkit, spikeextractors and spikewidgets should be merged in one unique code base"** is growing.

I was not part in previous discussion, so I don't have the global roadmap picture. Maybe you already discussed this in the past. I am sorry if this issue add extra noise in the global advanced of the project.

What I guess from code reading:
  * spikewidgets add some plotting utilities and some "widget" to explore results of some sorters.
  * some part of spikewidgets of have been ported to spike toolkit
  * spikewidgets offer some reporting tools (tables...)
  * spikeextractors is mainly an IO layer for reading traces from dataset or spikes from sorters
  * spiketoolkit offer:
    * a collection of sorter
    * tools for comparaison sorter results mainly the confusion matrix and some perfo metrics.

It would totally make sens to put evreything in the same module:
  * It would avoid
    ```python
    import spikeinterface as si
    import spikewidgets as sw
    import spiketoolkit as st
    ```
  * Change at spikeinterface API could propaged at the same time in spiketoolkit and every where 
    without depency challenge between teh 3 modules
  * Change at spiketoolkit API could propaged atomicaly too.
  * futur class of Sorter could be clearly link to there relative class SpikeExtractor
  * reading the code for external contributor would simpler
  * Each sub code name (spikeinterface, spiketoolkit, spikewidgets) clearly reflect what they do and what 
    is the goal.

For me, the global goal of his is RunSorter/extractResult/CompareResult/PlotResult/ReportResult.

So finding a new name for a unique module that incorporate the 3 ones could be valuable.
I am not native english and I am very bad for finding names but something sematicaly in the neiboorhood of "comparaison spike sorter", "benchmarch spike sorter" "validate spike sorter" would be cristal clear for external people.

All submodule (spiketoolkit.sorter, spiketoolkit.comparison, extractors...) have a very clear name.
So:
  * creating a new project with a new name
  * copy paste sub directory in this from from the 3 modules
  * fix all import lines

would not be a big work But it would be very usefull for futur raodmap and robust to refactoring.

Sorry for noise.

Samuel

**Comment by colehurwitz31** [comment] 2019-02-13 11:31
Hi Sam,

We have discussed this before and you bring up some excellent points. I can give you some insight into our design decision, but I think we will be able to clarify and brainstorm even better when we meet over Skype next week.

We decided to have each module be separated for number of reasons:

1) Spikeextractors was designed to be our most robust and stable module. It was the first one we created and it sits at the lowest level in the pipeline. It was made separate to keep dependencies low (it only requires numpy) and because users may _just_ want to use the extractors in their code. I know that Jeremy and I are using the extractors as part of other projects which don't necessarily need spiketoolkit since extractors are convenient for legacy code pipelines.

2) We wanted a clear separation of functionality between modules. Spikeextractors would handle file IO, spikewidgets would handle all visualization and widgets, and spiketoolkit would handle analysis, sorting, and evaluation. There shouldn't really be overlap between the repositories and any current overlap should probably be removed. We thought this would aid external contributors and users because each module has a clear purpose. We have struggled, however, with spiketoolkit, as it takes on a large portion of the work. We are still thinking about the best way to handle that module.

3) We created the SpikeInterface organization to encapsulate all three of the modules. This was our attempt to aggregate the repositories and give them an overarching connection.

If there is a way to create a repository that has each of the three modules as submodules, where we can update the original three modules and have that automatically update the aggregate repository, that would be a great addition. Do you have any ideas how to create something like this? The name would probably be something like SpikeInterface.

Hope that clarifies our current design decisions and I look forward to discussing this more next week!

Best,

Cole

**Comment by alejoe91** [comment] 2019-02-20 16:13
We could create a SpikeInterface with a custom installation that when calling the setup.py clones and installs the repos. I'm not sure this can be done automatically with the setup.py though.

Alternatively we can add a requirements.txt that installs through pip:

e.g
pip install -e git+https://github.com/SpikeInterface/spikeextractors.git@master#egg=spikeextractors
pip install -e git+https://github.com/SpikeInterface/spiketoolkit.git@master#egg=spiketoolkit
pip install -e git+https://github.com/SpikeInterface/spikewidgets.git@master#egg=spikewidgets

what do you guys think?

**Comment by colehurwitz31** [comment] 2019-02-20 16:27
I agree that having a module called, SpikeInterface, that automatically installs all three would be amazing if there is a feature like that.

Then, if you want to use that module by itself, we could have:

```
import spikeinterface as si

si.se.NumpyRecordingExtractor....
si.st....
si.sw....
```

**Comment by alejoe91** [comment] 2019-02-20 19:16
Hi Cole, 
I think that the first case would require to create a new package with physical copies of the 3 packages.

I was thinking more to something like a pic install SpikeInterface that automatically installs the 3 packages.
Then you can just use it as normal.

**Comment by samuelgarcia** [comment] 2019-02-20 19:32
```python
import spikeinterface as si

si.se.NumpyRecordingExtractor....
si.st....
si.sw....
```
is quite verbose


Making this with an empty package but just a \_\_init\_\_.py is quite easy to make.
```python
import spikeextractors as se
se.NumpyRecordingExtractor...
```

I don't think it is in top 5 priiority but we can keep the issue open.

**Comment by martinosorb** [comment] 2019-03-13 14:43
What was decided about this? If I can give my two cents, when I first worked on this a few days ago I was quite surprised I had to install three different repos just to get started... I would suggest this:

```python
import spikeinterface.toolkit as st
import spikeinterface.widgets as sw
import spikeinterface.extractors as se
```

**Comment by colehurwitz31** [comment] 2019-03-13 16:05
That does look very nice @martinosorb . As mentioned above, we originally separated the repos because it allowed for modular development and also let the user import and use spikeextractors separately (some may only use the spikeextractors).

However, if we can maintain the modular development of three repos, but implement your suggestion, I would be very happy with that. I really like the code snippet you posted.

**Comment by colehurwitz31** [comment] 2019-03-13 16:37
Maybe we can look into this:

**git slave**
Git slave can be useful if your workflow need to perform same git operations on multiple project related repositories.

Gitslave creates a group of related repositories—a superproject repository and a number of slave repositories—all of which are concurrently developed on and on which all git operations should normally operate; so when you branch, each repository in the project is branched in turn. Similarly when you commit, push, pull, merge, tag, checkout, status, log, etc; each git command will run on the superproject and all slave repositories in turn. This sort of activity may be very familiar to CVS and (to a lesser extent) Subversion users. Gitslave's design is for simplicity for normal git operations.

@alejoe91 @magland @samuelgarcia

**Comment by alejoe91** [comment] 2019-03-14 08:01
I would still keep the repos separate as they are designed to deal with different things.
If in the end we are going to deploy a GUI to set up a pipeline this will be all under the hood :)

@colehurwitz31 git slave could be investigated more. We have used submodules before and it's hard to deal with it.

**Comment by magland** [comment] 2019-03-14 09:55
I would prefer that SpikeExtractors, in particular, remain a separate package. It is a clean, lightweight, self-contained entity.

**Comment by alejoe91** [comment] 2019-05-02 18:39
@samuelgarcia I'll close this. I think we all agree now to have 3 repos :)

**Closed by alejoe91** 2019-05-02 18:39 UTC

**Comment by samuelgarcia** [comment] 2019-05-02 19:02
I am still not convinced to have 3 repos but I don't care :)
