### ISSUE TITLE
validation metrics do not agree

### ISSUE THREAD

**Issue by mhhennig** [SpikeInterface/spiketoolkit#113] opened 2019-05-09 20:29 UTC
I compared the results of a `sortingcomparison`, and they are inconsistent.

Example from the table returned by `sc.get_performance('by_spiketrain')`:

unit | tp_rate |	fn_rate | cl_rate | fp_rate_st1 | fp_rate_st2 | accuracy | sensitivity| precision | miss_rate | false_discovery_rate
-|-|-|-|-|-|-|-|-|-|-
0|0.516944|3.67605|0.516944|388.742|94.9095|0.13156|12.3288|0.132802|87.6712|99.8672

Result from `sc.get_false_negative_fraction(0)` and `sc.get_false_positive_fraction(0)`, and I get:

0.15623205054566336  0.5799256505576208

This looks inconsistent, is there a difference in how these are computed?

**Comment by alejoe91** [comment] 2019-05-09 20:31
I haven't checked the single functions lately. I think Jeremy wrote those in the first place. I think we should remove them and land on the get_performance call :)

I would trust the get_performance ones, but it's good to double check

**Comment by mhhennig** [comment] 2019-05-09 20:47
Ok, agree, that's good.
Does `sc.get_best_unit_match1(unit)` still do the right thing, i.e. return the one that has been established as the best match?

**Comment by alejoe91** [comment] 2019-05-09 20:54
Yes the matching should be the same

**Comment by samuelgarcia** [comment] 2019-05-10 07:18
I agree with @alejoe91 

If @magland wrote ```get_false_negative_fractio``` and ```get_false_positive_fraction``` , I am afraid that they are used in the spikeforest website.
I think theses metrics are bias because the fraction is done on len(units2) and should done on len(units1) like in get_performance().

I think that get_performance should also have a mode to return "raw_count" in a DataFrame with no fraction at all.

And if th issueis open, I would propose to remove percent scale (0-100) and replace by ratio scale (0-1).
We can keep 100 factor on print but not internally.
This percent scale will lead us to make mistake I guess.
Would you be OK to go the fraction ?

**Comment by alejoe91** [comment] 2019-05-10 14:29
I'm ok with this

**Comment by samuelgarcia** [comment] 2019-05-14 13:05
I will patch get_false_negative_fractio and get_false_positive_fraction and use internally get_performance.

This will avoid duplicate code that are not agree.

In the same PR I plan:
  * to go for scale [0-1]
  * export the dataframe of raw_count
  * count how many nott match units


OK ?

**Comment by samuelgarcia** [comment] 2019-05-14 13:07
I am reading again the entire code of SortingComparison.

What get_labels2 is for ? There is also something wrong in it.

**Comment by alejoe91** [comment] 2019-05-14 13:43
yeah it should be `self._sorting2.get_unit_ids()` and `self._labels_st2[unit_id]`.

It returns the spikes labels for a unit (TP, FP, FN, CL)

**Comment by samuelgarcia** [comment] 2019-05-14 14:05
OK.
It is not so easy.

The way it is written is diffrent the way get_performance is written.

In **get_agreement_fraction**, **get_false_positive_fraction**, **get_false_negative_fraction** not assumtiun is done about what is the groung truth wheras get_performance are written with GT in mind.

I think, by design they is a total ambiguity about SortingCOmparison is for and actually it deal with 3 things:
  * benchamark sorted units vs groud truth units. The part of the class I cleaned before
    for this only the best_match do count
  * computing some agrrement between 2 sorters without GT assumption, so the base tools for 
     MultiSortingComparison.

I think we should split this class into 2 classes so : one for GT comparison and one for agreement between 2 sorters.
Here we sadly mix everything at counting and at performence level.

**Comment by samuelgarcia** [comment] 2019-05-15 07:52
I am back and I insist: SortingComparison need refactroing!!

The same class serve 2 purposes (comparison witg GT and agreement between 2 sorters).
It is a mess because depending who writte the code and why the global logic differ a bit.
Some argument:
  * **get_performance** have no sens in context  agreement between sorters
  * **get_agreement_fraction**, ... have no sens for GT benchmark
  * matching logic is not the same we  known the GT or not
  * in GT context the fraction must done with len(units1) denominator
  * in Agreement context fraction must done with some kind on len(union(units1, units2))
  * GT logic should have more perf measurement for instance when we known that the GT is
     exhaustive (mearec)


So there are 2 options for factoring SortingComparison:
  1. keep a unique class but add a kargs **mode** that would be in ('ground_truth', 'agreement')
  2. separate the 2 classes but having a base class for everything is common. 

I prefer solution two but I don't want to impose anything.
@alejoe91 @magland @colehurwitz31 @mhhennig : what do you think ?

**Comment by alejoe91** [comment] 2019-05-15 08:06
3rd option: keep the same class with `mode` but add another function:

- `compare_sorter_to_ground_truth`

So in the end we will have 3 comparison functions:

- `compare_two_sorters`: compares to sorter outputs (no GT)  - runs SortingComparison mode **agreement** internally
- `compare_multiple_sorters`: compares multiple sorter ouputs - runs MultiSortingComparison (always mode **agreement**) internally
- `compare_sorter_to_ground_truth`: compares one sorter with ground truth - runs SortingComparison mode **ground_truth** internally

**Comment by colehurwitz31** [comment] 2019-05-15 08:11
I prefer solution two as well. I think that is the most clear coalition and would avoid any potential user errors

**Comment by samuelgarcia** [comment] 2019-05-15 08:11
Total agreement for having 3 functions that would the API.
Internally I think that keeping only one function with make the code a bit dirty with a lot of
```
if self.mode == 'GT':
   ...
elif self.mode == 'agrrement':
   ....
```

Having a design by class here is more cristal clear for a futur dev digging the code.
I wait other proposel.

**Comment by samuelgarcia** [comment] 2019-05-15 08:11
Lets wait Mtthias and maybe Jeremy ?

**Comment by colehurwitz31** [comment] 2019-05-15 08:13
I think having two functions would be best as Samuel mentioned. Having one function with a bunch of flags is messy and hard to debug. Also, the chance of errors by using the class directly would increase. 

Having three functions makes sense though

**Comment by alejoe91** [comment] 2019-05-15 09:00
So something like a `SortingComparison` (compares spike sorting output) and a `GroundTruthComparison` classes?

**Comment by samuelgarcia** [comment] 2019-05-15 09:09
OK with this.

**Comment by samuelgarcia** [comment] 2019-05-15 09:16
I start this afternoon.
I will need help for SortingComparison.get_agreement_fraction I think must change the den,ominator, any idea ?

**Comment by alejoe91** [comment] 2019-05-15 09:46
I think we can get rid of the get_agreement_fraction. The get performance by spike train already returns all the counting info.

In the sorter-sorter comparison we can label all the unmatched spikes for matched spike trains as `FP`, but we do not label as `FP` the unmatched units' spikes. Also we should not have false negatives in the sorter-sorter comparison. Maybe we can call the `FP`, unmatched spike `US` or something like that?

I think that `TP`, `FP`, and `FN` should be used when ground truth is known.

In case of sorter-sorter comparison, the rates by spike_trains is can be computed as: 2*#tp / (nb1 + nb2)., basically dividing by the total number of spikes for the 2 spike trains.

What do you guys think?

**Comment by samuelgarcia** [comment] 2019-05-15 11:19
(2*tp) / (nb1 + nb2) is OK.
We could also have : tp / union(unit1, unit2) equivalent to tp / (nb1 + nb2 - tp)


I propose to make the skeleton of this new refactoring.
Make GroundTruthComparison totally.
An leave SortingComparison open to further discussion.

See you soon on a PR.

**Comment by alejoe91** [comment] 2019-05-15 11:32
sounds good @samuelgarcia  :)

**Comment by samuelgarcia** [comment] 2019-05-15 12:00
I have strated teh skeleton for that.

at the moment I only copy methods and paste them in BaseComparison or GroundTruthComparison

**Comment by samuelgarcia** [comment] 2019-05-15 12:06
#121

**Comment by samuelgarcia** [comment] 2019-05-15 12:25
I am stupid
get_agreement_fraction is in fact compute_agreement_score wich already do 
tp / union(unit1, unit2) equivalent to tp / (nb1 + nb2 - tp)

So no mistake here.

**Comment by samuelgarcia** [comment] 2019-05-15 14:46
In this new refactoring are we OK that 
**FP (%ST2): {fp_rate_st2} %** is now useless and can be remove because ST2 is not the GT ?

**Comment by alejoe91** [comment] 2019-05-15 15:48
Yes :)

**Comment by alejoe91** [comment] 2019-05-24 17:08
I think fixed with the new refractoring

**Closed by alejoe91** 2019-05-24 17:08 UTC
