### ISSUE TITLE
Get_unit_templates when using NWB file slow (n_jobs not specified) or causes error (n_jobs specified)

### ISSUE THREAD

**Issue by lfrank** [SpikeInterface/spiketoolkit#389] opened 2020-09-01 20:50 UTC
When running get_unit_templates using a recording extractor generated from an NWB file, two problematic behaviors can occur:

1. If the n_jobs parameter is not specified, it takes at least 1 minute / unit for the unit_template to be generated. This may be because random access into an HDF5 dataset seems to be very slow.

2. if n_jobs is set (here set to 7), I get an error due to a failure to load an extension required for the NWB file. This error does not occur with sorting, so it must be specific to the parallelization get_unit_waveforms: 

```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/joblib/parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/joblib/parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py", line 1751, in _extract_waveforms_one_unit
    recording = se.load_extractor_from_dict(rec_arg)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spikeextractors/extraction_tools.py", line 677, in load_extractor_from_dict
    return BaseExtractor.load_extractor_from_dict(d)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spikeextractors/baseextractor.py", line 301, in load_extractor_from_dict
    extractor = _load_extractor_from_dict(d)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spikeextractors/baseextractor.py", line 318, in _load_extractor_from_dict
    extractor = _load_extractor_from_dict(kwargs[k])
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spikeextractors/baseextractor.py", line 318, in _load_extractor_from_dict
    extractor = _load_extractor_from_dict(kwargs[k])
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spikeextractors/baseextractor.py", line 318, in _load_extractor_from_dict
    extractor = _load_extractor_from_dict(kwargs[k])
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spikeextractors/baseextractor.py", line 349, in _load_extractor_from_dict
    extractor = cls(**kwargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spikeextractors/extractors/nwbextractors/nwbextractors.py", line 159, in __init__
    nwbfile = io.read()
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/backends/hdf5/h5tools.py", line 414, in read
    return call_docval_func(super().read, kwargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/utils.py", line 405, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/backends/io.py", line 36, in read
    container = self.__manager.construct(f_builder)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/manager.py", line 238, in construct
    result = self.__type_map.construct(builder, self, None)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/manager.py", line 857, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1105, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1035, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1085, in __get_sub_builders
    ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1035, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1077, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1090, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1090, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/manager.py", line 234, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/manager.py", line 857, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1105, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1035, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/build/objectmapper.py", line 1063, in __get_sub_builders
    for parent_dt in manager.namespace_catalog.get_hierarchy(ns, dt):
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/utils.py", line 561, in func_call
    return func(args[0], **pargs)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/hdmf/spec/namespace.py", line 327, in get_hierarchy
    raise KeyError("'%s' not a namespace" % namespace)
KeyError: "'ndx-franklab-novela' not a namespace"
"""

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-10-94a533a6265b> in <module>
----> 1 nd.common.SpikeSorting().populate()

~/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/datajoint/autopopulate.py in populate(self, suppress_errors, return_exception_objects, reserve_jobs, order, limit, max_calls, display_progress, *restrictions)
    157                     self.__class__._allow_insert = True
    158                     try:
--> 159                         make(dict(key))
    160                     except (KeyboardInterrupt, SystemExit, Exception) as error:
    161                         try:

~/Src/NWB/nwb_datajoint/nwb_datajoint/common/common_spikesorting.py in make(self, key)
    295             template_params['verbose'] = True
    296             print(f'template_params: {template_params}')
--> 297             unit_templates = st.postprocessing.get_unit_templates(recording_extractor, sort, **template_params)
    298             print(unit_templates[0])
    299             for unit_id in unit_ids:

~/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py in get_unit_templates(recording, sorting, unit_ids, channel_ids, mode, _waveforms, **kwargs)
    322     else:
    323         if _waveforms is None:
--> 324             waveforms = get_unit_waveforms(recording, sorting, unit_ids, channel_ids, return_idxs=False, **kwargs)
    325         else:
    326             waveforms = _waveforms

~/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py in get_unit_waveforms(recording, sorting, unit_ids, channel_ids, return_idxs, **kwargs)
    206                     arr = sorting.allocate_array(shape=shape, dtype=dtype, name=fname, memmap=memmap)
    207                     memmap_arrays.append(arr)
--> 208                 output_list = Parallel(n_jobs=n_jobs, backend=joblib_backend)(
    209                     delayed(_extract_waveforms_one_unit)(unit, rec_arg, sort_arg, channel_ids,
    210                                                          unit_ids, grouping_property,

~/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/joblib/parallel.py in __call__(self, iterable)
   1040 
   1041             with self._backend.retrieval_context():
-> 1042                 self.retrieve()
   1043             # Make sure that we get a last message telling us we are done
   1044             elapsed_time = time.time() - self._start_time

~/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/joblib/parallel.py in retrieve(self)
    919             try:
    920                 if getattr(self._backend, 'supports_timeout', False):
--> 921                     self._output.extend(job.get(timeout=self.timeout))
    922                 else:
    923                     self._output.extend(job.get())

~/opt/anaconda3/envs/nwbdj/lib/python3.8/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~/opt/anaconda3/envs/nwbdj/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

~/opt/anaconda3/envs/nwbdj/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

KeyError: "'ndx-franklab-novela' not a namespace"
```

**Comment by alejoe91** [comment] 2020-09-02 10:35
Hi @lfrank and thanks for the issue.

> * If the n_jobs parameter is not specified, it takes at least 1 minute / unit for the unit_template to be generated. This may be because random access into an HDF5 dataset seems to be very slow.

This is certainly right. As it stands NWB is not very fast. Do you perform some preprocessing steps? if you do, e.g. a filter, then the process will be even slower due to lazy filtering of single waveforms. In that case, I recommend using the caching mechanism (`rec = se.CacheRecordingExtractor(rec_nwb, 'cache-file-name.dat')`), to perform all the filtering, dump a binary copy of the data, and load a memmap object, which is much faster than accessing the NWB file.

> * if n_jobs is set (here set to 7), I get an error due to a failure to load an extension required for the NWB file. This error does not occur with sorting, so it must be specific to the parallelization get_unit_waveforms:

I'm not super familiar with nwb extensions and how they are installed. When n_jobs>1 then multiple processes are spawned. If `pynwb` requires the extension to be imported in order to load the extractor, this is probably the cause of the error. @bendichter any idea?

**Comment by samuelgarcia** [comment] 2020-09-02 10:38
In hdf5, for parallel  **read**I don't think we need an extention.
Do we force mode='r' when opening the NWB file ?

**Comment by alejoe91** [comment] 2020-09-02 10:40
@samuelgarcia the extension is an NWB type extension (ndx)

**Comment by bendichter** [comment] 2020-09-02 16:03
@lfrank regarding `n_jobs=7`: @alejoe91 and I think the issue here is that you need to `import ndx_franklab_novela` in order to read from your NWB files. You can do this in the beginning of the routine for a single job, but this would need to be called each time a new job is spun up, and it currently is not when using `n_jobs`. One solution I explored is to add the `load_namespaces=True` flag to the `NWBHDF5IO` calls. This would attempt to automatically infer the API from the cached schema within the NWB files, obviating the `ndx_franklab_novela` import. This will handle the problem for the majority of use-cases, but `load_namespaces` will fail for you because you define a `MultiContainerInterface` [here](https://github.com/NovelaNeuro/ndx-franklab-novela/blob/c994c711fa67c416a2ddfcc3bc58fd301dedceb5/src/pynwb/ndx_franklab_novela/nwb_image_series.py#L9-L31), which is currently not supported by API auto-generation. We are actively working on that now, with [the necessary changes](https://github.com/hdmf-dev/hdmf/pull/420) to hdmf merged 1 week ago. I haven't had a chance to test this in pynwb and work out the kinks, but I can start looking into that now. Getting that pushed through would have two effects for you:
1) using multiple jobs would work (or at least be one step closer to working)
2) you probably wouldn't have to `import ndx_franklab_novela` before reading your NWB files! (would still be required for write)

**Comment by alejoe91** [comment] 2020-09-02 16:12
@lfrank after talking to @bendichter we believe that the problem is the following:

In order for you to load the NWB file with the `'ndx-franklab-novela'` extension you probably need to `import ndx_franklab_novela` before. 

When multiple processes are spawned, the `'ndx-franklab-novela'` package is not available anymore, as it is not imported by sub-processes. We'll try to find a solution to this.

**Comment by lfrank** [comment] 2020-09-02 16:53
Thank all for you input.

I’ll try the caching mechanism to create the file as a first pass and then test out the package once the multiple process issue is fixed.

**Comment by alejoe91** [comment] 2020-10-16 16:30
Hi @lfrank 

Just merged a PR which makes extracting waveforms much faster! Even using a single job!
You can see some benchmarks in the comments: https://github.com/SpikeInterface/spiketoolkit/pull/399
All the benchmarks are on NWB files.

Let me know if that works well for you.

**Closed** 2020-11-20 14:19 UTC
