### ISSUE TITLE
compute_all_metric_data is slow on large dataset

### ISSUE THREAD

**Issue by teristam** [SpikeInterface/spiketoolkit#248] opened 2019-09-23 18:55 UTC
When calling `compute_all_metric_data`, in `postprocessing_tools._get_quality_metric_data`, `get_unit_amplitudes` will return the amplitude of all spike waveforms, which can be very slow for dataset with many spikes. There should be an option to specify a subset of the waveform to return. Usually it may not necessary to compute the metrics on all spikes.

**Comment by alejoe91** [comment] 2019-09-23 19:01
@teristam good point! We are actually updating the metric calculator on these days to fix these issues (plus others!) Will reference to the PR once it's open. @colehurwitz we should reduce the default number of spikes in all metrics

**Comment by colehurwitz** [comment] 2019-09-23 19:08
I think the challenge is that Josh's code expects all input arrays to have the same length as all spikes in the recording. See https://github.com/SpikeInterface/spikemetrics/blob/master/spikemetrics/metrics.py

I am not sure how to overcome this constraint.

**Comment by colehurwitz** [comment] 2019-09-23 19:09
We could do the epochs **before** the metrics are calculated rather than during. Josh's code takes in all the data and then does epochs.

**Comment by colehurwitz** [comment] 2019-09-23 19:19
Could we parallelize some of the post processing tools to make all of this faster?

**Comment by samuelgarcia** [comment] 2019-09-23 19:21
Hi @colehurwitz : I don't get this epoch stuff, sorry I did not have time to read the code.
I think we should hack the original code by adding **selected_spike_index** (or something like that) to reduce the number of spikes everywhere.
Ideally this  **selected_spike_index** would be one randomly once with a seed to ensure reproducibility.

**Comment by colehurwitz** [comment] 2019-09-23 19:21
Also, we maybe make a new function for computing all of the quality metric data except for amplitudes. Amplitudes are only used in the cutoff metric.

**Comment by colehurwitz** [comment] 2019-09-23 19:29
I think sub-selecting spikes might cause issues, Samuel. It would definitely bias ISI violations and presence ratios right?

**Comment by samuelgarcia** [comment] 2019-09-23 19:41
Totally, sorry. I had in mind waveform mostly.

**Comment by alejoe91** [comment] 2019-09-23 19:44
I think that for isi and presence using all spikes it's no problem as only spiketrains are used. The problem is when metrics that require wf and templates are used. In that case it's safe to use a subsample of the spikes as we compute the templates as the median

**Comment by colehurwitz** [comment] 2019-09-23 20:11
I think it is a bit challenging to change josh’s code for this.. maybe we can get Josh to work on that.

**Comment by colehurwitz** [comment] 2019-09-23 20:23
Do you think postprocessing tools is parallelizable as well @alijoe91?

**Comment by alejoe91** [comment] 2019-09-23 20:26
Who is @alijoe91?!? Eheheh 
Yes we can parallelize a few stuff. Several for loops that can be run in parallel

**Comment by colehurwitz** [comment] 2019-09-23 20:37
Whoops, phone typo 😅

So a couple of things we brain stormed here to improve performance:

1. Parallelize aspects of postprocessing.
2. Separate amplitudes from compute all metric data (only one metric uses it).
3. Sub sample spikes for feature metrics.

**Comment by alejoe91** [comment] 2019-09-23 20:46
Option 2 and 3 should be prioritized imo as they are quick changes

**Comment by colehurwitz** [comment] 2019-09-24 08:37
> I think that for isi and presence using all spikes it's no problem as only spiketrains are used. The problem is when metrics that require wf and templates are used. In that case it's safe to use a subsample of the spikes as we compute the templates as the median

Could you explain the part about the templates? I don't understand what you mean.

**Comment by alejoe91** [comment] 2019-09-24 08:46
The slow part is computing waveforms and wf-related info, like templates and pca. For the metrics that use these info (all isolation metrics and snr) we should use the a limited number of waveforms to speed things up. 
For ISI-violations and presence ratio, which don't use waveform info, we have to use all spikes and this won't affect performance as they are super fast to compute

**Comment by colehurwitz** [comment] 2019-09-24 08:50
So all we have to do is set the default values for max_num_waveforms and max_num_pca_waveforms to be smaller in this case? Am I understanding correctly>

**Comment by colehurwitz** [comment] 2019-09-24 08:51
> Hi @colehurwitz : I don't get this epoch stuff, sorry I did not have time to read the code.
> I think we should hack the original code by adding **selected_spike_index** (or something like that) to reduce the number of spikes everywhere.
> Ideally this **selected_spike_index** would be one randomly once with a seed to ensure reproducibility.

So what exactly is @samuelgarcia referring to? Does he also want to reduce waveforms?

**Comment by alejoe91** [comment] 2019-09-24 08:55
Yes I believe so :)

**Comment by alejoe91** [comment] 2019-09-24 08:55
I would just expose the `max_num_waveforms` and `max_num_pca_waveforms` and reduce the default values

**Comment by colehurwitz** [comment] 2019-09-24 08:57
I think they are exposed. I will reduce the default though. :)

**Comment by colehurwitz** [comment] 2019-09-24 11:22
So adjusting the waveforms will help with PCA, but won't have any affect on amplitudes.

Here is the slow part I think:

```
spike_train = sorting.get_unit_spike_train(unit_id)
        if max_num_amplitudes < len(spike_train):
            indices = np.random.RandomState(seed=seed).permutation(len(spike_train))[:max_num_amplitudes]
        else:
            indices = np.arange(len(spike_train))
        spike_train = spike_train[indices]

        snippets = recording.get_snippets(reference_frames=spike_train,
                                          snippet_len=[frames_before, frames_after])
        if peak == 'both':
            amps = np.max(np.abs(snippets), axis=-1)
            if len(amps.shape) > 1:
                amps = np.max(amps, axis=-1)
        elif peak == 'neg':
            amps = np.min(snippets, axis=-1)
            if len(amps.shape) > 1:
                amps = np.min(amps, axis=-1)
        elif peak == 'pos':
            amps = np.max(snippets, axis=-1)
            if len(amps.shape) > 1:
                amps = np.max(amps, axis=-1)
        else:
            raise Exception("'peak' can be 'neg', 'pos', or 'both'")
```

**Comment by colehurwitz** [comment] 2019-09-24 11:24
Maybe we could make an option for amplitudes to be for the templates rather than each individual spike?

```
method: str
        If 'absolute' (default), amplitudes are absolute amplitudes in uV are returned.
        If 'relative', amplitudes are returned as ratios between waveform amplitudes and template
        If 'template', amplitudes are returned as template amplitudes.
```

**Comment by colehurwitz** [comment] 2019-09-24 11:28
`max_num_amplitudes` is set to infinite by default.

**Comment by colehurwitz** [comment] 2019-09-24 11:57
I think the problem with this logic is that it looks at all snippets which is very costly. Not sure the best way around this.

**Comment by alejoe91** [comment] 2020-03-31 16:05
Added joblib processing and memmap backend. should speed up computations. Closing for now

**Closed by alejoe91** 2020-03-31 16:05 UTC
